version: '3'

services:
  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      mynetwork:
        ipv4_address: 172.19.0.2

  back:
    build:
      context: back
      dockerfile: Dockerfile
    environment:
      REDIS_SERVER: 172.19.0.2:6379
    depends_on:
      - redis
    ports:
      - "4000:4000"
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3

  front:
    build:
      context: front
      dockerfile: Dockerfile
    environment:
      BACKEND_API_URL: http://172.19.0.3
      CLIENT_API_URL: http://172.19.0.4
    depends_on:
      - back
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.19.0.4:3000/ping"]  
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3000:3000"
    networks:
      mynetwork:
        ipv4_address: 172.19.0.4

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.19.0.0/24
