name: devops-exersice


on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  workflow_dispatch:
  
jobs:

  bump-version:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
    
    - name: version-tag
      id: tag
      uses: anothrNick/github-tag-action@master 
      env:
          VERBOSE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs: 
        tag: ${{ steps.tag.outputs.tag }}
    

  build-docker:
    needs: [bump-version]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACTION_TOKEN }}
    
   
    - name: build redis
      run: |
          repository_owner=${{ github.repository_owner }}
          repository_owner_lowercase=$(echo "$repository_owner" | tr '[:upper:]' '[:lower:]')
          cd ./redis
          docker build -t ghcr.io/${repository_owner_lowercase}/redis:${{ github.sha }} -t  ghcr.io/${repository_owner_lowercase}/redis:${{ needs.bump-version.outputs.tag }}  -f ./redis/Dockerfile .
          docker push ghcr.io/${repository_owner_lowercase}/redis:${{ github.sha }} 
          docker push ghcr.io/${repository_owner_lowercase}/redis:${{ needs.bump-version.outputs.tag }}

    - name: build back
      run: |
          repository_owner=${{ github.repository_owner }}
          repository_owner_lowercase=$(echo "$repository_owner" | tr '[:upper:]' '[:lower:]')
          cd ./black
          docker build -t ghcr.io/${repository_owner_lowercase}/back:${{ github.sha }} -t ghcr.io/${repository_owner_lowercase}/back:${{ needs.bump-version.outputs.tag }} -f ./back/Dockerfile .
          docker push ghcr.io/${repository_owner_lowercase}/back:${{ github.sha }}
          docker push ghcr.io/${repository_owner_lowercase}/back:${{ needs.bump-version.outputs.tag }}
      


    - name: build front
      run: |
          repository_owner=${{ github.repository_owner }}
          repository_owner_lowercase=$(echo "$repository_owner" | tr '[:upper:]' '[:lower:]')
          cd ./front
          docker build -t ghcr.io/${repository_owner_lowercase}/front:${{ github.sha }} -t ghcr.io/${repository_owner_lowercase}/front:${{ needs.bump-version.outputs.tag }} -f ./front/Dockerfile .
          docker push ghcr.io/${repository_owner_lowercase}/front:${{ github.sha }}
          docker push ghcr.io/${repository_owner_lowercase}/front:${{ needs.bump-version.outputs.tag }}
      

    - name: build nginx
      run: |
          repository_owner=${{ github.repository_owner }}
          repository_owner_lowercase=$(echo "$repository_owner" | tr '[:upper:]' '[:lower:]')
          cd ./nginx
          docker build -t ghcr.io/${repository_owner_lowercase}/nginx:${{ github.sha }} -t ghcr.io/${repository_owner_lowercase}/nginx:${{ needs.bump-version.outputs.tag }} -f ./nginx/Dockerfile .
          docker push ghcr.io/${repository_owner_lowercase}/nginx:${{ github.sha }}
          docker push ghcr.io/${repository_owner_lowercase}/nginx:${{ needs.bump-version.outputs.tag }}
      