name: 'S3 bucket'

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore: 
      - '*'
    paths:
      - 'aws/global/s3'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Init'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Plan'
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}