name: 'S3 bucket'

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore: 
      - '*'
    paths:
      - 'aws/global/s3'
  workflow_dispatch:
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.6.0
          tf_actions_subcommand: ['init', 'plan']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    