name:  AWS S3 bucket destroy

on:
  workflow_dispatch:
    # Inputs the workflow expects.
    inputs:
      tfpath:
        description: 'aws/global/s3/'
        required: false
        default: 'aws/global/s3/'


jobs:
  
  tf_code_check:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest

    if:  ${{ inputs.tfpath }} 
    steps:
    - uses: actions/checkout@v2.5.0


    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2
    
    - name: Terraform init
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        echo "** Running Terraform Init**"
        terraform init

    - name: Terraform destroy
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        echo "** Running Terraform Migrate**"
        terraform init -migrate-state -force-copy
        echo "** Running Terraform Destroy**"
        terraform plan -destroy
        terraform destroy -auto-approve

    - name: add comment
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        git config user.name ${{ github.actor }}
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        sed -i '/backend "s3" {/,/}/ s/^/# &/' main.tf
        git add .
        git commit -m "Delete s3 bucket tf.state from aws"
        git push 
      working-directory: ${{ github.event.inputs.tfpath }}